add_newline = false

format = """$username$hostname$directory$character"""
right_format = """$all"""
palette = "catppuccin_mocha"
command_timeout = 1000

[username]
style_root = 'white bold'
style_user = 'sky bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold sky) '
disabled = false

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[golang]
format = '[ ](bold cyan)'

[gcloud]
disabled = true 

[python]
python_binary = 'python3'
detect_extensions = ['py']

[kubernetes]
symbol = '☸ '
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false
contexts = [
  { context_pattern = "pr-pa7", style = "green", context_alias = "pa7", symbol = " " },
  { context_pattern = "dv-par5", style = "blue", context_alias = "dv-par5", symbol = " " },
  { context_pattern = "pr-par5", style = "green", context_alias = "par5", symbol = " " },
  { context_pattern = "arn:aws:eks:eu-west-3:30", style = "green", context_alias = "omerxx", symbol = " " },
]

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

